### ISSUE TITLE
Can't start game by shortcut

### ISSUE THREAD

**Issue by TheOppaiDragon** [fa0311/DMMGamePlayerFastLauncher#124]
### OS

Windows 11

### Bug Description

The shortcut for DolphinWave dont launch because give me an error. 
How fix this?

### Error Message

```Shell
Traceback (most recent call last):
  File "launch.py", line 46, in thread
  File "launch.py", line 68, in launch
Exception: area not allowed
```

**Comment by TheOppaiDragon** [comment]
`Traceback (most recent call last):
  File "tab\shortcut.py", line 119, in fn
  File "tab\shortcut.py", line 183, in get_game_info
Exception: area not allowed
`

Another error when i recreate shortcut

**Comment by fa0311** [comment]
@TheOppaiDragon 
This is probably an error related to login.
- Please create a shortcut to start DMMGamePlayer. `shortcut->Fast Launch GamePlayer`
- Launch it
- Log in to DMM
- Close the DMM window

**Comment by TheOppaiDragon** [comment]
I got another error when i launch shortcut dmm

```
Traceback (most recent call last):
  File "launch.py", line 136, in thread
  File "launch.py", line 155, in launch
  File "lib\DGPSessionV2.py", line 122, in write
sqlite3.OperationalError: disk I/O error
```

**Comment by fa0311** [comment]
Uncheck  `バックグラウンド実行を許可する`

![image](https://github.com/fa0311/DMMGamePlayerFastLauncher/assets/34892635/3f3d62e1-7da5-4e0a-872e-25cb2fb07745)

**Comment by TheOppaiDragon** [comment]
Is already unckecked. In DMM launcher i logged in before installing DMMFastLauncher. I need logout to official launcher?

**Comment by fa0311** [comment]
Ummm, the behavior I am assuming is that importing an account into DMMFastLauncher will log me out of the official Launcher.
After restarting your PC,
Try logging into the official Launcher and import your account back into DMMFastLauncher


> Traceback (most recent call last):
>   File "launch.py", line 136, in thread
>   File "launch.py", line 155, in launch
>   File "lib\DGPSessionV2.py", line 122, in write
> sqlite3.OperationalError: disk I/O error

This error is very strange and means that some program is preventing the Official Launcher from accessing the stored data it has.
I don't know if the program that is preventing this is the official Launcher, DMMFastLauncher, or the antivirus software.

**Comment by TheOppaiDragon** [comment]
Okay i try that. Since i'm oversea i use a VPN to login into Official Launcher. Without can't login

**Comment by TheOppaiDragon** [comment]
Don't work. When i open shortcut created for DMM to login gave me this message
![image](https://github.com/fa0311/DMMGamePlayerFastLauncher/assets/29179424/832ff8f4-964a-4b0f-a817-c98d177a2c77)

**Comment by TheOppaiDragon** [comment]
I tried open shortcut where i need login with vpn and work, i closed that shortcut and i created shortcut for the game give me icon game and no error, i closed vpn open the game but give me same error

```
Traceback (most recent call last):
  File "launch.py", line 46, in thread
  File "launch.py", line 68, in launch
Exception: area not allowed
```

**Comment by fa0311** [comment]
VPN must be connected.
No ability to bypass request limits by country.
There is an option to use http proxy or sock5.

**Comment by TheOppaiDragon** [comment]
So i can't play game without using it? or maybe need only for login and after i can disable

**Comment by TheOppaiDragon** [comment]
> VPN must be connected. No ability to bypass request limits by country. There is an option to use http proxy or sock5.

How i can use option for http proxy / sock5?

**Comment by fa0311** [comment]
> How i can use option for http proxy / sock5?

Edit the proxy by selecting `Setting->Edit Shortcut`.
Also, some proxy-related bugs have been fixed in v5.6.0.

**Comment by TheOppaiDragon** [comment]
> > So i can't play game without using it? or maybe need only for login and after i can disable
> 
> Yes, to log in to DMM, you must connect from a specific region, even if you use FastLauncher.
> 
> > How i can use option for http proxy / sock5?
> 
> Edit the proxy by selecting `Setting->Edit Shortcut`. Also, some proxy-related bugs have been fixed in v5.6.0.
> 
> There are two options for the Proxy in FastLauncher The first is a proxy for all communications, including games The second is a proxy for communications related to the DMM login process. If both are set, the second takes precedence.
> 
> Some games (online games such as umamusume) require you to connect from certain countries.

And where i search these connection to put inside proxy? so maybe i dont use vpn amd use proxy to connect japan

**Comment by TheOppaiDragon** [comment]
I have my private server with OpenVPN for Japan connection. I used AWS by amazon to create idk if support proxy

**Comment by fa0311** [comment]
> I have my private server with OpenVPN for Japan connection. I used AWS by amazon to create idk if support proxy

ssh direct forwarding is available

Execute the following with the ssh client. PowerShell, etc. with ssh enabled.

`ssh -D localhost:1080 <user here>@<ip here>`

The settings in FastLauncher are as follows

`socks5://localhost:1080`

**Comment by TheOppaiDragon** [comment]
Where i need put setting in fastlauncher?
![image](https://github.com/fa0311/DMMGamePlayerFastLauncher/assets/29179424/bb6530fb-1ace-4cdc-8bc1-18d91b9b9684)

For the command: `ssh -D localhost:1080 <user here>@<ip here>` user here what need to put and for ip is ip from my vpn?

**Comment by fa0311** [comment]
> Where i need put setting in fastlauncher?

A `DMM Proxy` is always required.
The `Proxy` is optional and proxies the game.

> For the command: `ssh -D localhost:1080 <user here>@<ip here>` user here what need to put and for ip is ip from my vpn?

Yes, use the ip of the AWS instance for ip here.

How do you currently connect to AWS?
Find out how to connect to an AWS instance via ssh using Powershell

**Comment by fa0311** [comment]
![image](https://github.com/fa0311/DMMGamePlayerFastLauncher/assets/34892635/13604934-c976-474b-a482-c016bb093c15)

---

Besides using ssh, I found a server called [Dante](https://www.inet.no/dante/)

---

Or, we have confirmed that this one works too.
Performance is not very good, but it is easy to build
https://github.com/sequoiar/socks5
```sh
git clone https://github.com/sequoiar/socks5
node ./proxy.js
```

**Comment by TheOppaiDragon** [comment]
> > Where i need put setting in fastlauncher?
> 
> A `DMM Proxy` is always required. The `Proxy` is optional and proxies the game.
> 
> > For the command: `ssh -D localhost:1080 <user here>@<ip here>` user here what need to put and for ip is ip from my vpn?
> 
> Yes, use the ip of the AWS instance for ip here.
> 
> How do you currently connect to AWS? Find out how to connect to an AWS instance via ssh using Powershell

i connect to aws with openvpn. i have a file inside app

**Comment by TheOppaiDragon** [comment]
You have discord i need a fast reply so we can chat more fast and resolve this issue

**Comment by fa0311** [comment]
> You have discord i need a fast reply so we can chat more fast and resolve this issue

I do not reply on closed social media


Still need some support?
Please erect a separate http proxy server from OpenVPN or use the ssh command to connect to aws

**Comment by TheOppaiDragon** [comment]
I see on AWS tell me how to connect by SSH but idk how to figure out. 

When i try to do your command with ip told me AWS tell me this: `root@my ip aws: Permission denied (publickey).`

**Comment by fa0311** [comment]
> When i try to do your command with ip told me AWS tell me this: `root@my ip aws: Permission denied (publickey).`



Are the public and private key settings correct?
On Windows, the private key is placed in .ssh/*.pem in the user directory.

**Comment by TheOppaiDragon** [comment]
> > When i try to do your command with ip told me AWS tell me this: `root@my ip aws: Permission denied (publickey).`
> 
> Are the public and private key settings correct? On Windows, the private key is placed in .ssh/*.pem in the user directory.
> 
> Is your username correct? In AWS, it is usually ec2-user

How i can set public and private key?
How i can access to the user directory u told me?

idk where to see name. And my private server in aws is Debian-1

**Comment by fa0311** [comment]
private key: `C:Users/<name>/.ssh/`
I don't know how to use AWS in detail either.
As far as I can tell from the official documentation, it can be set up on the web.

**Comment by TheOppaiDragon** [comment]
Where say: `instance-user-name@instance-public-dns-name` first is my name of the machine Debian-1? 
For public dns name what mean?

**Comment by fa0311** [comment]
> first is my name of the machine Debian-1?

I don't know.

> For public dns name what mean?

Public DNS is a fully qualified domain (e.g. xxx.xxx.amazonaws.com)

**Comment by fa0311** [comment]
Do your own research before asking me.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connect-to-linux-instance.html#connection-prereqs-get-info-about-instance

**Comment by TheOppaiDragon** [comment]
Hello i'm try again to connect in my vpn amazon lightsail, i tried get helped with chatgpt without success. 

can you help me again? I downloaded socks5 from link u sent me.  
i started with command `node ./proxy,js` and say me this + error when i start the game

![image](https://github.com/fa0311/DMMGamePlayerFastLauncher/assets/29179424/c6df4913-845e-448d-98a2-ca3dec818e4d)
