### ISSUE TITLE
アカウントのインポートでエラー

### ISSUE THREAD

**Issue by KUSACHA** [fa0311/DMMGamePlayerFastLauncher#132]
Traceback (most recent call last):
  File "lib\toast.py", line 18, in _wrapper
  File "tab\account.py", line 78, in callback
  File "lib\DGPSessionV2.py", line 126, in read
sqlite3.OperationalError: disk I/O error

**Comment by fa0311** [comment]
#135 チュートリアル動画を作ったのでご覧ください。
恐らくバックグラウンドでDMM Game Launcherが起動していることが原因です。
