### ISSUE TITLE
Unable open database

### ISSUE THREAD

**Issue by estjava** [fa0311/DMMGamePlayerFastLauncher#140]
Traceback (most recent call last):
  File "lib\toast.py", line 18, in _wrapper
  File "tab\account.py", line 77, in callback
  File "lib\DGPSessionV2.py", line 101, in __enter__
sqlite3.OperationalError: unable to open database file

**Comment by fa0311** [comment]
Kill all running DMMGamePlayer and FastLauncher processes
Do not run DMMGamePlayer in the background.
