### ISSUE TITLE
Importing DMM account

### ISSUE THREAD

**Issue by awhawhaw** [fa0311/DMMGamePlayerFastLauncher#142]
I tried importing my DMM account to the fast launcher. I currently have DMM client open and am logged in. This is the error I got.

Traceback (most recent call last):
  File "lib\toast.py", line 18, in _wrapper
  File "tab\account.py", line 83, in callback
  File "lib\DGPSessionV2.py", line 122, in write
sqlite3.OperationalError: disk I/O error

**Comment by ankarakata** [comment]
me too. i got the error related to account. below is error i got

![image](https://github.com/user-attachments/assets/64aa26fb-8d88-47b4-ab94-34e102aae364)

`Traceback (most recent call last):
  File "lib\toast.py", line 18, in _wrapper
  File "tab\account.py", line 80, in callback
Exception: Import failed.

`

**Comment by SeiSilver** [comment]
I also got this error, here is the log error 

```
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: FPLC
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1: invalid start byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: _GRECAPTCHA
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 3: invalid start byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: latestlogin
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 2: invalid start byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: login_id2
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1: invalid start byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: password
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1: invalid start byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: FPGSID
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1: invalid start byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: adpf_uid
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1: invalid start byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: althash
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: check_done_login
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: check_done_login
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1: invalid start byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: ckcy
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: cklg
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: has_althash
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: login_id2
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: login_secure_id
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: password
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: secid
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: subscription_members_status
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: subscription_members_status
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1: invalid start byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: FPAU
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1: invalid start byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: FPID
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1: invalid start byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: _dd_s
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: ckcy
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1: invalid start byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: cklg
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1: invalid start byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: i3_ab
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1: invalid start byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: 
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1: invalid start byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: 
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1: invalid start byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: ss.sid
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 0: invalid continuation byte
[WARNING] [2024-11-25 10:25:21] Failed to decrypt cookie: ws.sid
Traceback (most recent call last):
  File "lib\DGPSessionV2.py", line 130, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 0: invalid continuation byte
[ERROR] [2024-11-25 10:25:21] Traceback (most recent call last):
  File "lib\toast.py", line 18, in _wrapper
  File "tab\account.py", line 80, in callback
Exception: Import failed.
```

**Comment by fa0311** [comment]
@awhawhaw 
> sqlite3.OperationalError: disk I/O error

Kill all running DMMGamePlayer and FastLauncher processes
Do not run DMMGamePlayer in the background.

@ankarakata @SeiSilver 
> Exception: Import failed.

Duplicate #143
