### ISSUE TITLE
アカウントのインポートに失敗する。

### ISSUE THREAD

**Issue by stm7128** [fa0311/DMMGamePlayerFastLauncher#143]
### OS

Windows 11 24H2

### 不具合の説明

GamePlayerの高速化から作成したショートカットでDMMGamePlayerを起動しようとした際、エラーが出て起動しなかったのでアカウントの再インポートを試そうとしたところ同様のエラーが出てどうにもできなくなった。
![image](https://github.com/user-attachments/assets/0105a295-5742-441b-ba9b-14a608fda1dd)

### エラーメッセージ

```Shell
Could not decode to UTF-8 column 'encrypted_value' with text 'v10�[��\��":����`��THf)\o��@V�6w�R>����6Lf��������<YI����R'i'
```

### ログ

```Shell
Traceback (most recent call last):
  File "lib\toast.py", line 18, in _wrapper
  File "tab\account.py", line 78, in callback
  File "lib\DGPSessionV2.py", line 126, in read
sqlite3.OperationalError: Could not decode to UTF-8 column 'encrypted_value' with text 'v10�[��\��":����`��THf)\o��@V�6w�R>����6Lf��������<YI����R'i'
```

**Comment by NCPereira** [comment]
Same here. Getting the exact same error.
