### ISSUE TITLE
インポートに失敗する

### ISSUE THREAD

**Issue by Applique-e** [fa0311/DMMGamePlayerFastLauncher#148]
バグでショートカットが機能しなくなったためDMMGamePlayerもFastLauncherも完全に削除した上で再インストールしたら、アカウントのインポートの部分で以下のエラーが出てインポートに失敗する。

```
Traceback (most recent call last):
  File "lib\toast.py", line 18, in _wrapper
  File "tab\account.py", line 80, in callback
Exception: インポートに失敗しました。
```
バックグラウンドで起動していないことは確認済み
DMMGamePlayerのバグを回避するためにバージョンは5.3.11をインストール
自動アップデート回避用にpendingフォルダをアクセス拒否にしている

**Comment by fa0311** [comment]
v5.8.0 は DMMGamePlayer v5.3.12 以降でのみ動作します

それでも解決せず `インポートに失敗しました。` や `login required` は発生する場合はこちらが原因かと思います
https://github.com/fa0311/DMMGamePlayerFastLauncher/issues/145#issuecomment-2501794512

**Comment by fa0311** [comment]
v6でも引き続き同じ問題が発生するのであれば再度issuesを作り直してください
