### ISSUE TITLE
フォルダ名に日本語を含めるとデコードエラーが発生する

### ISSUE THREAD

**Issue by fa0311** [fa0311/DMMGamePlayerFastLauncher#24]
Traceback (most recent call last):
  File "[http://DMMGamePlayerFastLauncher.py](https://t.co/mw9v1DFySd)", line 113, in <module>
  File "[http://DMMGamePlayerFastLauncher.py](https://t.co/mw9v1DFySd)", line 44, in get_dpg5_config
UnicodeDecodeError: 'cp932' codec can't decode byte 0x93 in position 35: illegal multibyte sequence

**Comment by fa0311** [comment]
自分の環境では再現できなかった

**Comment by SeliaMistral** [comment]
自分の環境だとdmmgame.cnf内のdefaultInstallDirとpathに日本語が含まれているため
DMMGamePlayerFastLauncher.pyの43行目

with open(dgp5_path + "dmmgame.cnf", "r") as `f:
                                     ⇩
with open(dgp5_path + "dmmgame.cnf", "r", encoding='utf-8') as f:

にすることで正常に動作するようになりました。
