### ISSUE TITLE
ログイン失敗 (Nonce cannot be empty)

### ISSUE THREAD

**Issue by southrop** [fa0311/DMMGamePlayerFastLauncher#60]
お世話になっております。4.8.0がリリースされたとのことで早速試しましたが、残念ながらDMM Game Player 5.2.1でログインできなかったことをご報告いたします。
```
Traceback (most recent call last):
  File "DMMGamePlayerFastLauncher.py", line 241, in <module>
  File "DMMGamePlayerFastLauncher.py", line 89, in error
Exception: Login failed
If DMMGamePlayer is running, exit it or Please start DMMGamePlayer and login again.
```

`--debug`` 追加するとこんな感じになります。
```
Traceback (most recent call last):
  File "DMMGamePlayerFastLauncher.py", line 212, in <module>
  File "DMMGamePlayerFastLauncher.py", line 95, in info
  File "DMMGamePlayerFastLauncher.py", line 210, in <module>
  File "lib\DGPSession.py", line 81, in read
  File "Crypto\Cipher\AES.py", line 228, in new
  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
  File "Crypto\Cipher\_mode_gcm.py", line 620, in _create_gcm_cipher
  File "Crypto\Cipher\_mode_gcm.py", line 188, in __init__
ValueError: Nonce cannot be empty
```

**Comment by ryomaco514** [comment]
当方でも同様のエラーがありました。
まずsample内のショートカットを起動した結果です。
![Unhandled exception in script 2023_03_23 14_40_08](https://user-images.githubusercontent.com/16443895/227114489-96d36e1b-d679-40f3-a111-5a17c71ff019.png)

ショートカットを自分で作り直すと異なるログが出ました。
![Screenshot 2023_03_23 14_37_35](https://user-images.githubusercontent.com/16443895/227114647-8b7d0f4d-02de-4653-b8cd-cbe07da4fd82.png)
ショートカットの作業フォルダのパスを自分のユーザ名にするとこうなるようです。
