### ISSUE TITLE
ショートカットが作れません

### ISSUE THREAD

**Issue by negimiku** [fa0311/DMMGamePlayerFastLauncher#84]
お世話になっております。

新しいv5.0.1を使ってみたのですが、うまく起動ショートカットが作れません。
作れないのは以下の5つで、なぜかウマ娘(umamusume)だけは最初に作成出来ました。

・プリコネR(priconner)
・デレステ(imascgstage)
・スロスト(slost)
・つなキャン△(yurucamp)
・エラゲ(404gr)

全てのタイトルのアカウント情報はインポート出来ています。
しかし、ショートカットが作れない5つのタイトルは、
作成しようとすると、以下の様なエラーが出ます。

Traceback (most recent call last):
  File "lib\toast.py", line 17, in _wrapper
  File "tab\shortcut.py", line 105, in bypass_callback
  File "tab\shortcut.py", line 133, in get_game_info
Exception: login required

なので、DMMGamePlayer5でログインして、
ショートカットを作りたいタイトルを起動・終了をしたのですが、
やはり同じエラーが出てショートカットが作れません。
アカウント情報も作り直したりしてからやってみても同じでした。
なぜウマ娘だけ正常にショートカットが作れたのか分かりません。

また、ショートカット作成を2回以上試そうとすると、

Traceback (most recent call last):
  File "lib\toast.py", line 17, in _wrapper
  File "tab\shortcut.py", line 114, in save_callback
  File "tab\shortcut.py", line 94, in save
  File "utils\utils.py", line 28, in file_create
FileExistsError: そのファイルは既に存在します。

というエラーが出てしまいます。
ショートカットが正常に作成出来ない場合でも、
shortcutフォルダに該当タイトルの.jsonファイルが出来てしまい、
そのファイルを削除しないと再度ショートカット作成を試せません。
（編集→削除をするか、shortcutフォルダの.jsonを削除のどちらかをしないといけない）

正常に作成出来たウマ娘のショートカットからの起動は
今のところ、どんな条件でも（時間は掛かりますが）起動出来ます。
まだ起動時のゲーム自動更新が出来ているかは分からないのですが…。

あと、ランチャー起動ショートカット作成で作ったショートカットを起動しても、
DMMGamePlayer5のログインまでは出来るのですが（ログインを求められる事もあります…仕方ないですが）、
その後該当タイトルが起動されません。
ショートカットは作成済みアカウントの物全て作れます。

宜しくお願いします。

**Comment by fa0311** [comment]
`Exception: login required` というエラーが出た場合の対処法です。
1. DMMGamePlayerFastLauncher で該当アカウントの `ランチャーのショートカット` を作成する。(既に作成済みの場合は省略)
2. ショートカットを起動してログインする。
3. DMMGamePlayer5 のロードが完了したらバツを押して DMMGamePlayer5 閉じる

DMMGamePlayerFastLauncherにインポート済みのアカウントで直接起動した DMMGamePlayer5 にログインしないでください。
ショートカット経由で起動した DMMGamePlayer5 を使用しているときは DMMGamePlayerFastLauncher で同一のアカウントを使用しないでください。(ゲームの起動、ショートカットの作成など)


> なぜウマ娘だけ正常にショートカットが作れたのか分かりません。

ウマ娘だけ別のアカウントですか？

> ショートカットが正常に作成出来ない場合でも、
> shortcutフォルダに該当タイトルの.jsonファイルが出来てしまい、
> そのファイルを削除しないと再度ショートカット作成を試せません。

これは意図しない動作なので次のアップデートで修正する予定です。

**Comment by negimiku** [comment]
ふぁさん
こんにちは、お疲れ様です。

> Exception: login required というエラーが出た場合の対処法です。

ショートカット作成が出来ないというのは、.jsonまでは作成されるのですが、
（デスクトップに）ショートカットアイコンが作成されないという事です。

DMMGamePlayer起動中にFastLauncherで作成されたショートカットから
ゲームの起動を行う等の2重ログインの様な事ではありません。

> ウマ娘だけ別のアカウントですか？

はい、そうです。
…だったのですが、ショートカットアイコンからウマ娘を起動しようとしたら
「login required」のエラーが出る様になってしまい、
DMMGamePlayerを起動したらウマ娘のアップデートが来ていました。
（ショートカット起動ではアップデートが行われなかったみたいです）
この状態ではDMMGamePlayerでアップデートを行い、
ゲームを起動するまでショートカット起動が出来ないので、
DMMGamePlayerからアップデートを行い、そのままゲームを起動・終了したのですが、
作成済みのウマ娘ショートカットからは「login required」のエラーが出てしまい、
アカウントのインポートし直しを行ったりしたのですが、
ゲームの起動もショートカットの作成し直しも出来なくなりました。
代わりに、なぜかプリコネRのショートカットの作成が出来て、起動も出来ています…。
他のゲームのショートカットの作成は、やはり「login required」のエラーが出てしまい、
schtasksフォルダの,xmlファイルとshortcutフォルダの.jsonファイル作成止まりで
ショートカットアイコンまでは作成されません。

ランチャー作成で作ったショートカットからゲームが直接起動しないのは
理由がよく分かりません…DMMGamePlayetまでは立ち上がるので
引数の渡しがうまく行っていないのでしょうか。

（FastLauncherのゲーム起動ショートカットからゲーム起動・終了後に
ランチャー作成のゲーム起動ショートカットを起動すると
必ずログインメールアドレスとパスワードの入力をしなければならないので
あまり使うものではないと思いますが…。
セキュリティ対策なのか嫌がらせなのか分かりませんが、
この場合や2重ログイン後に必ずアカウント入力を催促されますが、
メールアドレスとパスワードの入力欄が、
入力情報保持のチェックボックスを入れていても毎回クリアされるのが嫌すぎですね）

**Comment by fa0311** [comment]
> ショートカット作成が出来ないというのは、.jsonまでは作成されるのですが、
> （デスクトップに）ショートカットアイコンが作成されないという事です。

ショートカット作成も同様でゲームのアイコン情報などを取得するためログイン情報が必要です。(v5.0.2でログインに失敗した際にデフォルトのアイコンを使用するように変更予定です)

> （FastLauncherのゲーム起動ショートカットからゲーム起動・終了後に ランチャー作成のゲーム起動ショートカット（またはDMMGamePlayer）を起動すると 必ずログインメールアドレスとパスワードの入力をしなければならない

これおかしな動作ですね🤔
`アカウント` -> `編集` を確認したときに全て消えてしまっていますよね？

**Comment by negimiku** [comment]
すみません、なんか色々と状況が変わってしまっています。
現在、こちらの全6タイトル全てのショートカットの作成と起動が出来る様になっています。
ショートカットを作成するまでの方法は次の通りです。

（account, schtasks, shortcutフォルダ内のファイルを全部削除してから）
・DMMGamePlayerからショートカットを作成したいゲームを起動する
・起動したゲームを閉じる
・DMMGamePlayerを閉じる
・FastLauncherで起動したゲームのアカウントのインポートをする
・FastLauncherで起動したゲームのショートカットを作成する
（「起動時にゲームの自動更新」のチェックを入れ、「UAC自動昇格」のショートカットを作成）

↑この順で全てエラーが出ていない事を確認しながら全てのゲームのショートカットが作成出来ました。

ふとインポートされたアカウント情報ファイル（.byte）を見て気付いたのですが、
先程ウマ娘以外のショートカットが作成出来なかった時のアカウント情報ファイルのファイルサイズと
全ショートカットが正常に作成出来た現在のアカウント情報ファイルのファイルサイズは違います。
以前のファイルは全て削除してしまっているので正確なファイルサイズは分からないのですが、
現在のファイルサイズより間違いなく小さいものばかりでした。

…と色々と確認しながらこの文章を書いているのですが、先程まで正常にショートカット起動出来ていた物が
突然また「login required」エラーが出る様になって起動出来なくなってしまい、
DMMGamePlayerでログインし直したりしたのですがダメだったので、
アカウント情報のインポートし直しから始めようと.byteファイルを見てみたら、
ファイルサイズが小さくなっていました…どうしてそうなるのか、条件がよく分かりません。

> これおかしな動作ですね🤔
> アカウント -> 編集 を確認したときに全て消えてしまっていますよね？
>
> 消えているのであれば原因の切り分けをしたいのでこれらを確認してもらっていいですか？

「アカウント -> 編集」で内容が正常な場合は、
ランチャー作成で作ったショートカットからDMMGamePlayerを起動した時、
アカウント入力を催促された時には入力欄は保持されています。
2重ログイン後など行った後に「DMMGamePlayerを直接起動した時」、入力欄はクリアされます。
…という事みたいなので、インポートしたアカウント情報ファイルが正常な場合には
アカウント入力欄は保持されたままの様です。
そもそも、アカウント情報ファイル(.byte)が無い場合はDMMGamePlayerが起動する以前にエラーになりますし。

…しかし、今、アカウント情報ファイルのサイズが小さくなってしまっていて
FastLauncherで作成したショートカット起動で「login required」エラーが出る状態の物の
ランチャー作成で作ったショートカットから起動をすると、
アカウント入力欄はクリアされていません…小さくなった情報ファイルでも大丈夫な時もあるんですね（汗）。

DMMGamePlayerでのゲーム起動とFastLauncherのショートカットでのゲーム起動の2重ログイン（2重起動）後、
FastLauncherショートカットから起動するとセッション切れエラーが出る様になってしまいますが、
こうなってしまったらアカウント情報の再インポートからやり直しをするしかないのでしょうか？

あと、気になったのですが、ショートカット作成時の「ファイル名」欄には
作成したいショートカットのファイル名を指定するのだと思っていたのですが、
実際に作成されるショートカットのファイル名はゲームのフルタイトル名になってしまうんですね。
例えばファイル名欄に「デレステ」と入力してデレステのショートカットを作成すると
出来上がったショートカットのファイル名はファイル名入力欄の内容に関係なく
「アイドルマスター シンデレラガールズ スターライトステージ」になってしまいます。
この動作は合っていますが？

…長くて読み辛く、申し訳ありません（汗）。

**Comment by fa0311** [comment]
![image](https://github.com/fa0311/DMMGamePlayerFastLauncher/assets/34892635/6937d6c4-8269-45fe-92cf-8746e2aa58eb)
DMMGamePlayer の設定を確認できますか？
`バックグラウンド実行を許可する` にチェックが入っている場合、正常に動作しないみたいです
